version: 2.1

jobs:
  check-internet-access:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Test Internet Access
          command: |
            echo "Testing access to Google..."
            curl -I https://www.google.com || echo "Failed to reach Google"
            
            echo "Testing access to SonarSource..."
            curl -I https://get.sonarsource.com || echo "Failed to reach SonarSource"
workflows:
  version: 2
  test:
    jobs:
      - check-internet-access
