version: 2.1

executors:
  windows-executor:
    machine:
      enabled: true
    environment:
      SONAR_TOKEN: $SONAR_TOKEN  # Add your SonarQube token as an environment variable
      SONAR_PROJECT_KEY: $Root9-max_Root9-max  # Your SonarQube project key
      SONAR_PROJECT_NAME: $sidiq  # Name of your project

jobs:
  sonar-scanner:
    executor: windows-executor
    steps:
      - checkout  # Checks out your code to the job environment
      - run:
          name: Install Java 17
          command: |
            choco install openjdk17
            java -version  # Verify that Java 17 is installed correctly
      - run:
          name: Install SonarQube Scanner
          command: |
            Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-windows.zip" -OutFile "sonar-scanner-cli.zip"
            Expand-Archive -Path sonar-scanner-cli.zip -DestinationPath C:\sonar-scanner
            setx PATH "$env:PATH;C:\sonar-scanner\sonar-scanner-4.6.2.2472-windows\bin"
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner ^
              -Dsonar.projectKey=$Root9-max_Root9-max ^
              -Dsonar.projectName=$sidiq ^
              -Dsonar.sources=. ^
              -Dsonar.host.url=https://sonarcloud.io ^
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonar-scanner

