version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-server-2019  # Ensures a Windows environment on CircleCI
    environment:
      SONAR_TOKEN: $SONAR_TOKEN
      SONAR_PROJECT_KEY: $Root9-max_Root9-max
      SONAR_PROJECT_NAME: $sidiq

jobs:
  sonar-scanner:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install Java 17
          shell: powershell.exe  # Use PowerShell for this command
          command: |
            Invoke-WebRequest -Uri "https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip" -OutFile "C:\jdk17.zip"
            Expand-Archive -Path "C:\jdk17.zip" -DestinationPath "C:\java"
            [System.Environment]::SetEnvironmentVariable('JAVA_HOME', 'C:\java\jdk-17', 'Machine')
            [System.Environment]::SetEnvironmentVariable('Path', $Env:Path + ';C:\java\jdk-17\bin', 'Machine')
            java -version
      - run:
          name: Install SonarQube Scanner
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-windows.zip" -OutFile "C:\sonar-scanner-cli.zip"
            Expand-Archive -Path "C:\sonar-scanner-cli.zip" -DestinationPath "C:\sonar-scanner"
            [System.Environment]::SetEnvironmentVariable('Path', $Env:Path + ';C:\sonar-scanner\sonar-scanner-4.6.2.2472-windows\bin', 'Machine')
      - run:
          name: Run SonarQube Analysis
          shell: powershell.exe
          command: |
            sonar-scanner `
              -Dsonar.projectKey=$Env:Root9-max_Root9-max `
              -Dsonar.projectName=$Env:sidiq `
              -Dsonar.sources=. `
              -Dsonar.host.url=https://sonarcloud.io `
              -Dsonar.login=$Env:SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonar-scanner
