version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Choose the appropriate Docker image for your project
    steps:
      - checkout  # Checkout the code from your GitHub repository
      - run:
          name: Install dependencies
          command: |
            # Install SonarScanner
            curl -sS https://get.sonarsource.com/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip -o sonar-scanner.zip
            unzip sonar-scanner.zip -d /opt/sonar-scanner
            echo 'export PATH=$PATH:/opt/sonar-scanner/sonar-scanner-4.7.0.2747-linux/bin' >> ~/.bashrc
            source ~/.bashrc
      - run:
          name: Run SonarCloud analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.organization=your_organization \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN  # SONAR_TOKEN should be an environment variable in CircleCI

workflows:
  version: 2
  build:
    jobs:
      - build

