version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          - DNS_SERVER: "8.8.8.8"  # Google's DNS server
    steps:
      - run:
          name: Test DNS Resolution
          command: |
            echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
            curl -sS https://get.sonarsource.com/sonarscanner | sudo bash
