version: 2.1

executors:
  windows-executor:
    machine:
      enabled: true
    environment:
      SONAR_TOKEN: $SONAR_TOKEN  # SonarQube token
      SONAR_PROJECT_KEY: $Root9-max_Root9-max  # Project key
      SONAR_PROJECT_NAME: $sidiq  # Project name

jobs:
  sonar-scanner:
    executor: windows-executor
    steps:
      - checkout  # Checks out your code
      - run:
          name: Install Java 17
          command: |
            Invoke-WebRequest -Uri "https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip" -OutFile "jdk17.zip"
            Expand-Archive -Path jdk17.zip -DestinationPath C:\java
            setx JAVA_HOME "C:\java\jdk-17" /M
            setx PATH "%PATH%;C:\java\jdk-17\bin" /M
            java -version  # Verify installation
      - run:
          name: Install SonarQube Scanner
          command: |
            Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-windows.zip" -OutFile "sonar-scanner-cli.zip"
            Expand-Archive -Path sonar-scanner-cli.zip -DestinationPath C:\sonar-scanner
            setx PATH "%PATH%;C:\sonar-scanner\sonar-scanner-4.6.2.2472-windows\bin" /M
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner ^
              -Dsonar.projectKey=$Root9-max_Root9-max ^
              -Dsonar.projectName=$sidiq ^
              -Dsonar.sources=. ^
              -Dsonar.host.url=https://sonarcloud.io ^
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - sonar-scanner
