version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Or whatever your project's base image is
    working_directory: ~/repo

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Adjust to your project's image if necessary
    steps:
      - checkout  # Check out the code from GitHub

      # Install dependencies (including SonarScanner)
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk curl  # Make sure Java & curl are installed
            curl -sS https://get.sonarsource.com/sonarscanner | sudo bash  # Install SonarScanner

      # Run the SonarCloud scan
      - run:
          name: Run SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.organization=your_organization_id \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN  # Replace with your SonarCloud token, set as environment variable

workflows:
  version: 2
  build:
    jobs:
      - build
