version: 2.1

jobs:
  check-internet-access:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Test Internet Access
          command: |
            curl -I https://get.sonarsource.com
            curl https://www.google.com
workflows:
  version: 2
  test:
    jobs:
      - check-internet-access
