version: 2.1

# Define jobs and workflows in CircleCI
jobs:
  # Job to run the SonarCloud scan
  sonarcloud-scan:
    docker:
      - image: circleci/python:3.7  # Adjust this image to match your project's language (e.g., use a Java, Node, or Python image)
    steps:
      - checkout  # Checkout the code
      - run:
          name: Install dependencies
          command: |
            # Install any dependencies required for your project (e.g., Java, Node.js)
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk  # Example for Java (adjust for your stack)
      - run:
          name: Install SonarScanner
          command: |
            # Download and install SonarScanner
            wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-4.7.0.2747-linux.zip
            unzip sonar-scanner-4.7.0.2747-linux.zip
            export SONAR_SCANNER_HOME=$(pwd)/sonar-scanner-4.7.0.2747-linux
            export PATH=$PATH:$SONAR_SCANNER_HOME/bin
      - run:
          name: Run SonarCloud analysis
          command: |
            # Run the SonarCloud analysis on your code
            sonar-scanner \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.organization=your_sonarcloud_organization \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN  # Use CircleCI environment variable for security

workflows:
  version: 2
  build:
    jobs:
      - sonarcloud-scan
